selenide.browser=chrome
selenide.headless=false
selenide.browserSize=1920x1200
selenide.timeout=10000
selenide.pageLoadTimeout=30000
selenide.reportsFolder=target/reports/selenide
selenide.downloadsFolder=target/reports/download
selenide.screenshots=true
selenide.savePageSource=true
selenide.assertionMode=STRICT

